### ISSUE TITLE
zpeters speedtest results differ (at least for me) from python version

### ISSUE THREAD

**Issue by ipsecguy** [nlamirault/speedtest_exporter#2]
Hi,

I get different (lower) measurements with the speedtest version used in this exporter.

When using this speedtest for absolute measurements I advise to validate the results with the speedtest-cli as well as the official tools of Ookla before making a judgement speed.

Andreas

**Comment by nlamirault** [comment]
On *develop* branch, i update to use last version of speedtest from Zpeters.

**Comment by neilmunday** [comment]
I've also found that this exporter reports my download speed is a lot less (40Mbps) than that experienced using speedtest.net and the Python prometheus-speedtest module.

**Comment by Prof-Bloodstone** [comment]
I'm having similar issue.

For me, the highest download measured using this exporter is 56Mb/s, with average of 35Mb/s.

When using speed test on the same machine (both browser and CLI version), I get around 360-490Mb/s.

This sadly makes this exporter useless, since I don't even know what it tries to show.

I'm running version 0.3.0 of docker image.
